
version: '3.8'

services:
  backend:
    build: ./backend
    image: kanishk2404/tweet-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    # Previous bind mounts for reference:
    #   - ./backend/uploads:/app/uploads
    #   - ./backend/database.sqlite:/app/database.sqlite
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    image: kanishk2404/tweet-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  uploads_data:
  db_data: