services:
  backend:
    image: kanishk2404/tweet-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    # Persistent storage for uploads and database:
    # uploads_data: stores all uploaded images
    # db_data: stores the SQLite database in /app/db/database.sqlite
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app/db
    restart: unless-stopped

  frontend:
    image: kanishk2404/tweet-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:

# Usage:
# 1. Run: docker compose -f docker-compose.prod.yml up -d
# 2. Access frontend at http://localhost:3000
# 3. Enter your API keys on the web page after the app loads
