version: '3.8'

services:
  backend:
    build: ./backend
    image: kanishk2404/tweet-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      # This command now uses 'curl', which we will add in the backend Dockerfile
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        # CRITICAL CHANGE: Use the public address the browser can access
        - VITE_API_URL=http://localhost:5000
    image: kanishk2404/tweet-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped